/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Drillimpact (https://sketchfab.com/Drillimpact)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-green-wizard-gnome-n64-style-7708c9dd60234693a6dcb326d66c627f
Title: The Green Wizard Gnome N64 Style
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei/native'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Stick_Wizard_Gnome_0: THREE.Mesh
    Object_9: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Wizard_Gnome: THREE.MeshStandardMaterial
  }
}

// type ActionName =
//   | 'Wizard_Gnome_Armature|agree'
//   | 'Wizard_Gnome_Armature|Curse'
//   | 'Wizard_Gnome_Armature|disagree'
//   | 'Wizard_Gnome_Armature|Fall'
//   | 'Wizard_Gnome_Armature|Hit'
//   | 'Wizard_Gnome_Armature|idle'
//   | 'Wizard_Gnome_Armature|Walking'
// type GLTFActions = Record<ActionName, THREE.AnimationAction>

const ActionName =  'Wizard_Gnome_Armature|disagree'

export default function Greenwizard(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF(require('../assets/models/greenwizard.glb')) as GLTFResult
  const { actions } = useAnimations(animations, group)

  

  useEffect(()=>{
    actions[ActionName]?.play();

  },[])
 
  return (
    <group ref={group} {...props} dispose={null} scale={5}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Wizard_Gnomefbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Wizard_Gnome" />
                <group name="Wizard_Gnome_Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_6">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_9"
                      geometry={nodes.Object_9.geometry}
                      material={materials.Wizard_Gnome}
                      skeleton={nodes.Object_9.skeleton}
                    />
                    <group name="Object_8" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

